version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    command: sleep infinity
    ports:
      - "3000:3000"
    <<: &base
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - .:/myapp
      depends_on:
        - db
      environment:
        MYSQL_HOST: db
  css:
    command: bin/rails tailwindcss:watch
    tty: true
    <<: *base
